version: '3.2'

services:
  app:
    image: airsonic/airsonic:10.5.0-RELEASE
    container_name: airsonic
    restart: always
    user: '99'
    #ports:
    #  - '4040:4040'
    networks:
      - reverse-proxy
    volumes:
      - /mnt/data/scimetis.net/home/yohan/music:/music:z
      - /mnt/data/dossier_de_travail/home_airsonic:/airsonic/data:z

networks:

  reverse-proxy:
    external: true
